# Generated by Django 3.2.8 on 2021-10-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_notesofuser_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesofuser',
            name='image1',
            field=models.ImageField(blank=True, upload_to='notes'),
        ),
    ]
