# Generated by Django 3.2.8 on 2021-10-31 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_notesofuser_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotesOfUser',
        ),
    ]
